export const ARTICLE_DATABASE_PROVIDER = 'ARTICLE_DATABASE';
export const ARTICLE_REPOSITORY_PROVIDER = 'ARTICLE_REPOSITORY';
export const enum ARTICLE_USECASE_PROVIDERS {
  GET_ARTICLE = 'GET_ARTICLE_USECASE',
  GET_ARTICLES = 'GET_ARTICLES_USECASE',
  SET_ARTICLE = 'SET_ARTICLE_USECASE',
  DELETE_ARTICLE = 'DELETE_ARTICLE_USECASE',
  UPDATE_ARTICLE = 'UPDATE_ARTICLE_USECASE',
}
