export const FIRESTORE_PROVIDER = 'FIRESTORE';
export const FIRESTORE_OPTIONS_PROVIDER = 'FIRESTORE_OPTIONS';
export enum FIRESTORE_COLLECTION_PROVIDERS {
  USERS = 'users',
  ARTICLES = 'articles',
}
